"""empty message

Revision ID: 1f5cceed79e6
Revises: 3530e32b4b1c
Create Date: 2023-08-01 18:21:00.599289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5cceed79e6'
down_revision = '3530e32b4b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cafe_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('None', type_='foreignkey')
        batch_op.create_foreign_key("cafe_id", 'cafe', ['cafe_id'], ['id'])
        batch_op.create_foreign_key("users_id", 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user'], ['id'])
        batch_op.drop_column('cafe_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
