"""empty message

Revision ID: 3530e32b4b1c
Revises: b4ab9fa1f789
Create Date: 2023-08-01 12:22:56.465891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3530e32b4b1c'
down_revision = 'b4ab9fa1f789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_column('map_url')

    # ### end Alembic commands ###
