"""empty message

Revision ID: 54997efe0f8d
Revises: 1f5cceed79e6
Create Date: 2023-08-01 22:18:25.066837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54997efe0f8d'
down_revision = '1f5cceed79e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
