"""empty message

Revision ID: b4ab9fa1f789
Revises: df99941da6a9
Create Date: 2023-07-30 23:26:27.639536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ab9fa1f789'
down_revision = 'df99941da6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_constraint('liked_by', type_='foreignkey')
        batch_op.drop_column('liked_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('liked_by', 'users', ['liked_by'], ['id'])

    # ### end Alembic commands ###
