"""empty message

Revision ID: df99941da6a9
Revises: 
Create Date: 2023-07-30 18:19:28.280249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df99941da6a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_by', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('img_url',
               existing_type=sa.TEXT(length=500),
               type_=sa.String(length=250),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=250),
               nullable=True)
        batch_op.alter_column('has_sockets',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('has_toilet',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('has_wifi',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('can_take_calls',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('seats',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('coffee_price',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key('liked_by', 'users', ['liked_by'], ['id'])
        batch_op.drop_column('map_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_url', sa.TEXT(length=500), nullable=False))
        batch_op.drop_constraint('liked_by', type_='foreignkey')
        batch_op.alter_column('coffee_price',
               existing_type=sa.String(),
               type_=sa.TEXT(length=250),
               existing_nullable=True)
        batch_op.alter_column('seats',
               existing_type=sa.String(),
               type_=sa.TEXT(length=250),
               existing_nullable=True)
        batch_op.alter_column('can_take_calls',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('has_wifi',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('has_toilet',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('has_sockets',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=250),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(length=250),
               nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(length=500),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('liked_by')

    # ### end Alembic commands ###
